// <auto-generated />
using System;
using BankersSeat.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankersSeat.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BankersSeatDbContext))]
    partial class BankersSeatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "OwnerId", "OwnerType")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.GameSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateSnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.HasIndex("Id", "SessionVersion");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.IdempotencyRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ActorParticipantId", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.JoinLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LinkToken")
                        .IsUnique();

                    b.HasIndex("SessionId", "ExpiresAtUtc");

                    b.ToTable("join_links", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.LedgerPostingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "AccountId");

                    b.HasIndex("TransactionId", "Id");

                    b.ToTable("ledger_postings", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.LedgerTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrectsTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CorrectsTransactionId");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("ledger_transactions", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("JoinOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReconnectSecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Id")
                        .IsUnique();

                    b.HasIndex("SessionId", "JoinOrder")
                        .IsUnique();

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.PlayerFieldValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ParticipantId");

                    b.HasIndex("SessionId", "ParticipantId", "FieldId")
                        .IsUnique();

                    b.ToTable("player_field_values", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.SessionMetadataEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("LastAccessedAtUtc");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("session_metadata", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.SessionTtlPolicyEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoDeleteOnComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("IsArchived");

                    b.ToTable("session_ttl_policies", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.TemplateSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowPlayerOverdraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartingPlayerBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "EditionId", "TemplateVersion");

                    b.ToTable("template_snapshots", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.UserAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAuthenticatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHashBcrypt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.TemplateShareEntity", b =>
                {
                   b.Property<Guid>("Id")
                       .ValueGeneratedOnAdd()
                       .HasColumnType("TEXT");

                   b.Property<DateTime>("GrantedAtUtc")
                       .HasColumnType("TEXT");

                   b.Property<DateTime?>("RevokedAtUtc")
                       .HasColumnType("TEXT");

                   b.Property<Guid>("SharedByUserId")
                       .HasColumnType("TEXT");

                   b.Property<string>("SharedWithEmail")
                       .IsRequired()
                       .HasMaxLength(256)
                       .HasColumnType("TEXT");

                   b.Property<string>("TemplateId")
                       .IsRequired()
                       .HasMaxLength(100)
                       .HasColumnType("TEXT");

                   b.HasKey("Id");

                   b.HasIndex("GrantedAtUtc");

                   b.HasIndex("SharedByUserId");

                   b.HasIndex("SharedWithEmail");

                   b.HasIndex("TemplateId", "SharedWithEmail");

                   b.ToTable("template_shares", (string)null);
                });

            modelBuilder.Entity("BankersSeat.Server.Infrastructure.Persistence.Entities.TemplateMetadataEntity", b =>
                {
                   b.Property<Guid>("Id")
                       .ValueGeneratedOnAdd()
                       .HasColumnType("TEXT");

                   b.Property<string>("Author")
                       .IsRequired()
                       .HasMaxLength(200)
                       .HasColumnType("TEXT");

                   b.Property<string>("AuthorEmail")
                       .HasMaxLength(256)
                       .HasColumnType("TEXT");

                   b.Property<string>("AuthorUrl")
                       .HasMaxLength(500)
                       .HasColumnType("TEXT");

                   b.Property<int>("DownloadCount")
                       .HasColumnType("INTEGER");

                   b.Property<string>("EditionId")
                       .IsRequired()
                       .HasMaxLength(100)
                       .HasColumnType("TEXT");

                   b.Property<string>("FlagReasons")
                       .HasColumnType("TEXT");

                   b.Property<string>("License")
                       .IsRequired()
                       .HasMaxLength(50)
                       .HasColumnType("TEXT");

                   b.Property<string>("ModerationStatus")
                       .IsRequired()
                       .HasMaxLength(32)
                       .HasColumnType("TEXT");

                   b.Property<Guid>("OwnerUserId")
                       .HasColumnType("TEXT");

                   b.Property<DateTime>("PublishedAtUtc")
                       .HasColumnType("TEXT");

                   b.Property<string>("TemplateId")
                       .IsRequired()
                       .HasMaxLength(100)
                       .HasColumnType("TEXT");

                   b.Property<string>("TemplateStatus")
                       .IsRequired()
                       .HasMaxLength(32)
                       .HasColumnType("TEXT");

                   b.Property<DateTime>("UpdatedAtUtc")
                       .HasColumnType("TEXT");

                   b.HasKey("Id");

                   b.HasIndex("ModerationStatus");

                   b.HasIndex("OwnerUserId");

                   b.HasIndex("TemplateStatus");

                   b.HasIndex("TemplateId", "EditionId")
                       .IsUnique();

                   b.HasIndex("UpdatedAtUtc");

                   b.ToTable("template_metadata", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
